# Generated by Django 4.2.30 on 2026-09-28 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brief', models.TextField(blank=True, default='')),
                ('goals', models.TextField(blank=True, default='')),
                ('success_metrics', models.JSONField(blank=True, default=list)),
                ('target_audience', models.TextField(blank=True, default='')),
                ('regions', models.JSONField(blank=True, default=list)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('staging_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('complete', 'Complete'), ('archived', 'Archived')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='wda_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, choices=[('project_lead', 'Project Lead'), ('designer', 'Designer'), ('developer', 'Developer'), ('senior_developer', 'Senior Developer'), ('technical_lead', 'Technical Lead'), ('qa_tester', 'QA Tester'), ('qa_lead', 'QA Lead'), ('woocommerce_specialist', 'WooCommerce Specialist'), ('seo_specialist', 'SEO Specialist'), ('copywriter', 'Copywriter'), ('client_lead', 'Client Lead'), ('requirements_agent', 'Requirements Agent'), ('ux_agent', 'UX Agent'), ('design_assistant', 'Design Assistant'), ('wordpress_developer_agent', 'WordPress Developer Agent'), ('plugin_developer_agent', 'Plugin Developer Agent'), ('woocommerce_setup_agent', 'WooCommerce Setup Agent'), ('content_agent', 'Content Agent'), ('seo_agent', 'SEO Agent'), ('qa_agent', 'QA Agent'), ('performance_agent', 'Performance Agent'), ('security_agent', 'Security Agent'), ('documentation_agent', 'Documentation Agent')], default='', max_length=40)),
                ('kind', models.CharField(choices=[('human', 'Human'), ('ai', 'AI')], default='human', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('client_access', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['name'],
            },
        ),
    ]
