# Generated by Django 4.2.30 on 2026-09-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blocks',
            field=models.JSONField(blank=True, default=list, help_text='Page layout blocks for the product detail page.'),
        ),
        migrations.AddField(
            model_name='service',
            name='blocks',
            field=models.JSONField(blank=True, default=list, help_text='Page layout blocks for the service detail page.'),
        ),
    ]
