# Generated by Django 4.2.30 on 2026-09-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('resource', 'Resource'), ('schedule', 'Schedule'), ('budget', 'Budget'), ('client', 'Client'), ('security', 'Security'), ('compliance', 'Compliance'), ('other', 'Other')], default='other', max_length=20)),
                ('mitigation', models.TextField(blank=True, default='')),
                ('client_visible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('mitigating', 'Mitigating'), ('resolved', 'Resolved'), ('accepted', 'Accepted')], default='identified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'kind': 'human'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to='projects.teammember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risks',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('decision_type', models.CharField(choices=[('client_facing', 'Client Facing'), ('financial', 'Financial'), ('security', 'Security'), ('production', 'Production'), ('scope', 'Scope'), ('technical', 'Technical'), ('process', 'Process')], default='technical', max_length=20)),
                ('client_visible', models.BooleanField(default=True)),
                ('outcome', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_decisions', to='projects.teammember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('decision_type', models.CharField(choices=[('client_facing', 'Client Facing'), ('financial', 'Financial'), ('security', 'Security'), ('production', 'Production'), ('scope', 'Scope')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(limit_choices_to={'kind': 'human'}, on_delete=django.db.models.deletion.PROTECT, related_name='gating_approvals', to='projects.teammember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_gates', to='projects.project')),
            ],
            options={
                'verbose_name': 'Approval Gate',
                'verbose_name_plural': 'Approval Gates',
                'ordering': ['-created_at'],
            },
        ),
    ]
