# Generated by Django 4.2.30 on 2026-09-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('blocked', 'Blocked'), ('in_progress', 'In Progress'), ('internal_review', 'Internal Review'), ('client_review', 'Client Review'), ('approved', 'Approved'), ('done', 'Done')], default='not_started', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('inputs', models.TextField(blank=True, default='')),
                ('outputs', models.TextField(blank=True, default='')),
                ('acceptance_criteria', models.TextField(blank=True, default='')),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('approval_gate', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_assistants', models.ManyToManyField(blank=True, limit_choices_to={'kind': 'ai'}, related_name='assigned_workstreams', to='projects.teammember')),
                ('contributors', models.ManyToManyField(blank=True, related_name='contributed_workstreams', to='projects.teammember')),
                ('human_owner', models.ForeignKey(limit_choices_to={'kind': 'human'}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_workstreams', to='projects.teammember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstreams', to='projects.project')),
            ],
            options={
                'verbose_name': 'Workstream',
                'verbose_name_plural': 'Workstreams',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('blocked', 'Blocked'), ('in_progress', 'In Progress'), ('internal_review', 'Internal Review'), ('client_review', 'Client Review'), ('approved', 'Approved'), ('done', 'Done')], default='not_started', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('definition_of_done', models.TextField(blank=True, default='')),
                ('client_input_required', models.BooleanField(default=False)),
                ('client_input_text', models.TextField(blank=True, default='')),
                ('staging_reference', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='projects.teammember')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_tasks', to='workstreams.task')),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'kind': 'human'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_tasks', to='projects.teammember')),
                ('workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workstreams.workstream')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('phase', models.CharField(choices=[('discovery', 'Discovery'), ('architecture', 'Architecture and Planning'), ('design', 'Design'), ('build', 'Build'), ('qa', 'QA and Hardening'), ('launch', 'Launch'), ('post_launch', 'Post-Launch')], max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['phase'],
            },
        ),
        migrations.AddConstraint(
            model_name='workstream',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_workstream_per_project'),
        ),
    ]
